### PR TITLE
fix: Fixed copy+paste error in the implementation of `sample_people`. Fixes #638.

### LINKED ISSUE #638: Bug in `sample_people`
There are two bugs in `sample_people`:

1. The first is a copy+paste error in the implementation of `sample_multiple_l_reservoir`.
    - The weight is not initialized and updated correctly for sampling `n` items.
    - `Container` does not need to implement `HasLen`
2. Even after correcting (1), it's not sampling correctly. Sampling `n` items for small `n` does not seem to manifest the behavior, but sampling 100 items from 1000 gives results like:

```
[Person 99, Person 1, Person 2, Person 3, Person 4, Person 5, Person 6, Person 7, Person 8, Person 9, Person 10, Person 11, Person 12, Person 13, Person 14, Person 15, Person 101, Person 17, Person 18, Person 19, Person 20, Person 21, Person 22, Person 23, Person 24, Person 25, Person 26, Person 27, Person 28, Person 29, Person 30, Person 31, Person 32, Person 33, Person 34, Person 35, Person 36, Person 37, Person 38, Person 39, Person 40, Person 41, Person 42, Person 43, Person 44, Person 45, Person 100, Person 47, Person 48, Person 49, Person 50, Person 51, Person 52, Person 110, Person 54, Person 55, Person 56, Person 57, Person 58, Person 59, Person 60, Person 61, Person 62, Person 63, Person 64, Person 65, Person 66, Person 67, Person 68, Person 69, Person 70, Person 71, Person 72, Person 111, Person 74, Person 75, Person 76, Person 77, Person 78, Person 79, Person 80, Person 81, Person 82, Person 83, Person 84, Person 85, Person 86, Person 87, Person 88, Person 89, Person 90, Person 91, Person 92, Person 93, Person 94, Person 142, Person 96, Person 97, Person 98, Person 419]
```

This is clearly not right.

### PR DESCRIPTION
**Pull request by RobertJacobsonCDC**
The bug and its cause are detailed on the original issue #638.

This PR is not ready to merge until I add a reasonable statistical test in the unit test for `sample_people`.

### CODE REVIEW

File: src/random/sampling_algorithms.rs [hunk 1]
```diff
@@ -220,3 +222,70 @@ where
...
+mod tests {
+    use rand::rngs::StdRng;
+    use rand::SeedableRng;
+
+    use super::*;
+
+    #[test]
+    fn test_sample_multiple_l_reservoir_basic() {
+        let data: Vec<u32> = (0..1000).collect();
+        let seed: u64 = 42;
```
Comment (KOVALW) [inline src/random/sampling_algorithms.rs]: It doesn't take much comp time to add an iterator here, i.e.

```rust
for seed in 0..n_reps {
  [test]
}
```
with `n_reps<<1000` so that you don't expect it to fail. (works fine for 100 reps for example)
 
but the single replicate is fine
